In [11]:
#Import Dependencies
import requests
import json
import numpy as np
import pandas as pd


base_url = "https://www.fema.gov/api/open/"
disasterV1 = "v1/FemaWebDisasterSummaries"
#filterDate = "$filter=declarationDate gt '2004-10-31T04:00:00.000z'"
#sortBy = "$orderby=state"
#+"?"+filterDate+"&"+sortBy
grant_response = requests.get(base_url+disasterV1).json()
#print(json.dumps(grant_response,indent=4, sort_keys=True))


#v1_df = pd.DataFrame(grant_response["FemaWebDisasterSummaries"][0],
                     #grant_response["FemaWebDisasterSummaries"][12])
#v1_df

In [39]:
disasterV2 = "v2/HazardMitigationGrantProgramDisasterSummaries"
filters = "$filter=declarationDate gt '2004-10-31T04:00:00.000z' and incidentType eq 'Hurricane'"
sortBy = "$orderby=state"
disas_response = requests.get(base_url+disasterV2+"?"+filters+"&"+sortBy).json()
#print(json.dumps(disas_response,indent=4, sort_keys=True))

disasterNumber = []
dateLst = []
incidentTypeLst = []
stateLst = []
i = "HazardMitigationGrantProgramDisasterSummaries"

for x in range (len(disas_response[i])):
    disasterNumber.append(disas_response[i][x]["disasterNumber"])
    dateLst.append(disas_response[i][x]["declarationDate"])
    incidentTypeLst.append(disas_response[i][x]["incidentType"])
    stateLst.append(disas_response[i][x]["state"])

data = {"Disaster ID":disasterNumber, "Date Reported":dateLst, "Incident Type":incidentTypeLst, "State": stateLst}
        
    
v2_df = pd.DataFrame(data)
v2_df

,Disaster ID,Date Reported,Incident Type,State
0,1866,2009-12-22T00:00:00.000Z,Hurricane,Alabama
1,4563,2020-09-20T00:00:00.000Z,Hurricane,Alabama
2,1789,2008-09-10T00:00:00.000Z,Hurricane,Alabama
3,1593,2005-07-10T00:00:00.000Z,Hurricane,Alabama
4,4573,2020-12-10T00:00:00.000Z,Hurricane,Alabama
...,...,...,...,...
124,4335,2017-09-07T00:00:00.000Z,Hurricane,Virgin Islands of the U.S.
125,1807,2008-10-29T00:00:00.000Z,Hurricane,Virgin Islands of the U.S.
126,4340,2017-09-20T00:00:00.000Z,Hurricane,Virgin Islands of the U.S.
127,1939,2010-09-28T00:00:00.000Z,Hurricane,Virgin Islands of the U.S.
128,4093,2012-11-27T00:00:00.000Z,Hurricane,West Virginia

In [34]:
info = v2_df[v2_df["Disaster ID"]==4162]
info

    Disaster ID             Date Reported Incident Type State
12         4162  2014-01-23T00:00:00.000Z  Severe Storm    AK
22         4162  2014-01-23T00:00:00.000Z  Severe Storm    AK
34         4162  2014-01-23T00:00:00.000Z  Severe Storm    AK
55         4162  2014-01-23T00:00:00.000Z  Severe Storm    AK